// Generated by CoffeeScript 1.7.1
var access_parameters, access_token, coordsToAddr, count, displayPopularTag, distance, getDataFromFoursquareForLocation, getDataFromInstagram, getPopularLocations, initialUpdate, instaAuthorized, updateByAddr, updateByCoords, updatePhotosByCoords, updatePhotosByTag;

getDataFromInstagram = function(instagram_data, appendPhotos) {
  var comments, i, key, likes, photo, photoCode, photos, type, url_formatted;
  if (instagram_data.meta.code === 200) {
    console.log('instagram_data.meta.code = ' + instagram_data.meta.code);
    if (instagram_data.pagination) {
      if (instagram_data.pagination.next_url) {
        url_formatted = instagram_data.pagination.next_url.replace(/access_token=[^&]+&/, "").replace(/callback=[^&]+/, "callback=?");
        $("button.btn.next").unbind("click").click(function() {
          $(this).button("loading");
          return updatePhotosByTag("tag", url_formatted);
        });
      }
    }
    photos = instagram_data.data;
    if (photos.length > 0) {
      if (appendPhotos !== true) {
        $("#photos").empty();
      }
      i = $("#photos .row.pics .col-md-2").length;
      for (key in photos) {
        photo = photos[key];
        type = void 0;
        if (photo.type === "image") {
          type = "<div id=\"type\"><i class=\"fa fa-camera-retro\"></i></div>";
        } else {
          type = "<div id=\"type\"><i class=\"fa fa-film\"></i></div>";
        }
        likes = "<div id=\"likes\"><i class=\"fa fa-heart-o\"></i>" + " " + photo.likes.count + "</div>";
        comments = "<div id=\"comments\"><i class=\"fa fa-comment-o\"></i>" + " " + photo.comments.count + "</div>";
        photoCode = "<div class=\"col-md-2 grid cs-style-3\">" + "<div class=\"thumbnail hover\"><figure>" + "<img class=\"img-" + i + "\" src=\"" + photo.images.thumbnail.url + "\"><figcaption>" + type + likes + comments + "</figcaption></figure></div></div>";
        if (Math.round(i / 6) === i / 6) {
          $("#photos").append("<div class=\"row pics\"></div>");
        }
        $("#photos .row").last().append(photoCode);
        $("img.img-" + i).unbind("click").click({
          url: photo.images.standard_resolution.url,
          width: photo.images.standard_resolution.width,
          height: photo.images.standard_resolution.height,
          photo: photo
        }, function(e) {
          var code, description, link;
          if ($(".row.pics.tmp").length !== 0) {
            $(".row.pics.tmp").remove();
          }
          if (e.data.photo.type === "image") {
            if (e.data.photo.images.high_resolution) {
              link = e.data.photo.images.high_resolution.url;
            } else if (e.data.photo.images.standard_resolution) {
              link = e.data.photo.images.standard_resolution.url;
            } else {
              link = e.data.photo.images.low_resolution.url;
            }
            code = "<div class=\"row pics tmp\">" + "<div class=\"col-md-8 text-center\">" + "<img class=\"img-thumbnail tmp\" src=" + link + " alt=\"...\">" + "</div>" + "</div>";
          } else {
            if (e.data.photo.videos.high_resolution) {
              link = e.data.photo.videos.high_resolution.url;
            } else if (e.data.photo.videos.standard_resolution) {
              link = e.data.photo.videos.standard_resolution.url;
            } else {
              link = e.data.photo.videos.low_resolution.url;
            }
            code = "<div class=\"row pics tmp\">" + "<div class=\"col-md-8 text-center\">" + "<video class=\"img-thumbnail tmp\" controls autoplay loop>" + "<source src=" + link + ">" + "</video>" + "</div>" + "</div>";
          }
          $(code).insertAfter($(this).parent().parent().parent().parent());
          description = "<div class=\"col-md4\">" + "<p><a href=\"" + e.data.photo.link + "\"><h1>" + e.data.photo.user.username + "</h1></a></p>" + "<img class=\"img-thumbnail\" src=\"" + e.data.photo.user.profile_picture + "\">" + "</div>";
          return $("img.img-thumbnail.tmp, video.img-thumbnail.tmp").animate({
            width: e.data.width,
            height: e.data.height
          }, 500, function() {
            return $(this).parent().after(description);
          });
        });
        i++;
      }
    } else {
      $("#status").text("Hmm. I couldn’t find anything!");
    }
    $("#searchButtonGeo").button("reset");
    $("#searchButtonTag").button("reset");
    return $("button.btn.next").button("reset");
  }
};

initialUpdate = function() {
  var showPosition;
  showPosition = function(position) {
    var userLat, userLng;
    userLat = position.coords.latitude;
    userLng = position.coords.longitude;
    coordsToAddr(userLat, userLng);
    return updateByCoords(userLat, userLng);
  };
  if (navigator.geolocation) {
    return navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    return $("#status").text("Geolocation is not supported by this browser.");
  }
};

updateByAddr = function(address) {
  var geocoder;
  geocoder = new google.maps.Geocoder();
  return geocoder.geocode({
    address: address
  }, function(results, status) {
    var res;
    if (status === google.maps.GeocoderStatus.OK) {
      $("#status").text(results[0].formatted_address);
      addrToUrl(results[0].formatted_address);
      res = results[0].geometry.location;
      initializeMaps(res.lat(), res.lng());
      updatePhotosByCoords(res.lat(), res.lng());
      return getPopularLocations(res.lat(), res.lng());
    } else {
      return $("#status").text("Geocode was not successful for the following reason: " + status);
    }
  });
};

coordsToAddr = function(lat, lng) {
  var geocoder, latlng;
  geocoder = new google.maps.Geocoder();
  latlng = new google.maps.LatLng(lat, lng);
  return geocoder.geocode({
    latLng: latlng
  }, function(results, status) {
    if (status === google.maps.GeocoderStatus.OK) {
      if (results[1]) {
        $("#status").text(results[1].formatted_address);
        return addrToUrl(results[1].formatted_address);
      }
    } else {
      return $("#status").text("Geocoder failed due to: " + status);
    }
  });
};

updateByCoords = function(lat, lng) {
  initializeMaps(lat, lng);
  return updatePhotosByCoords(lat, lng);
};

updatePhotosByCoords = function(lat, lng) {
  var instagramUrl;
  console.log('updatePhotosByCoords');
  instagramUrl = "https://api.instagram.com/v1/media/search?lat=" + lat + "&lng=" + lng + "&distance=" + 50 + "&callback=?";
  return $.getJSON(instagramUrl, access_parameters, getDataFromInstagram);
};

updatePhotosByTag = function(tag, nextUrl) {
  var appendPhotos, instagramUrl;
  instagramUrl = "https://api.instagram.com/v1/tags/" + tag + "/media/recent" + "?count=" + count + "&callback=?";
  if (nextUrl) {
    appendPhotos = true;
    return $.getJSON(nextUrl, access_parameters, function(instagram_data) {
      return getDataFromInstagram(instagram_data, true);
    });
  } else {
    $.getJSON(instagramUrl, access_parameters, getDataFromInstagram);
    return tagToUrl(tag);
  }
};

getPopularLocations = function(lat, lng) {
  var foursquareUrl;
  foursquareUrl = "https://api.foursquare.com/v2/venues/explore?ll=" + lat + "," + lng + "&oauth_token=BUGNB0B2ML1KT4HDKWGI1MECXSKJDRJDO21QNZZLRRGEVYQQ&v=20140509" + "&venuePhotos=1";
  return $.getJSON(foursquareUrl, getDataFromFoursquareForLocation);
};

getDataFromFoursquareForLocation = function(foursquare_data) {
  var error, i, lat, lng, locations, popular, _results;
  if (foursquare_data.meta.code === 200) {
    locations = foursquare_data.response.groups[0].items;
    console.log('foursquare_data.response.groups[0].items = ' + "'" + foursquare_data.response.groups[0].items.length + "'");
    $("#popularLoc").empty();
    if (foursquare_data.response.groups[0].items.length !== 0) {
      i = 0;
      _results = [];
      while (i < 5) {
        lat = locations[i].venue.location.lat;
        lng = locations[i].venue.location.lng;
        popular = "<button type=\"button\" class=\"btn button-popularLoc btn-default btn-xs btn-popular-" + i + "\">" + locations[i].venue.name + "</button>";
        $("#popularLoc").append(popular);
        $(".btn-popular-" + i).unbind("click").click({
          lat: lat,
          lng: lng
        }, function(e) {
          updateByCoords(e.data.lat, e.data.lng);
          return coordsToAddr(e.data.lat, e.data.lng);
        });
        _results.push(i++);
      }
      return _results;
    }
  } else {
    error = foursquare_data.meta.errorDetail;
    return $("#status").text("Something happened, Foursquare said: " + error);
  }
};

displayPopularTag = function() {
  var i, popularTags, tagName, tags, _results;
  $("#popularTag").empty();
  tags = ["love", "tbt", "cute", "happy", "beautiful", "fun", "food", "art", "best", "day", "nature"];
  i = 0;
  _results = [];
  while (i < tags.length) {
    tagName = tags[i];
    popularTags = "<button type=\"button\" class=\"btn button-popular-tag btn-default btn-sm btn-popular-tag-" + i + "\">" + tagName + "</button>";
    $("#popularTag").append(popularTags);
    $(".btn-popular-tag-" + i).unbind("click").click({
      tag: tagName
    }, function(e) {
      return updatePhotosByTag(e.data.tag);
    });
    _results.push(i++);
  }
  return _results;
};

instaAuthorized = function() {
  if ($.cookie("insta_token")) {
    $("#auth").css("display", "none");
    return $("#notauth").removeAttr("style");
  } else {
    $("#auth").removeAttr("style");
    return $("#notauth").css("display", "none");
  }
};

access_token = $.cookie("insta_token");

access_parameters = {
  access_token: access_token
};

distance = 5000;

count = 24;

$(document).ready(function() {
  var addr, res, str, tag;
  if (window.location.href.match(/#access_token=.+/)) {
    str = window.location.href.match(/#access_token=.+/);
    res = str[0].replace("#access_token=", "");
    $.cookie("insta_token", res, {
      expires: 7,
      path: "/"
    });
  }
  instaAuthorized();
  if (window.location.href.match(/#addr-.+/)) {
    addr = window.location.href.match(/#.+/)[0].replace(/#addr-/, "").replace(/-/g, " ");
    updateByAddr(addr);
  } else if (window.location.href.match(/#tag-.+/)) {
    tag = window.location.href.match(/#.+/)[0].replace(/#tag-/, "");
    updatePhotosByTag(tag);
    if (!$("#tagButton").attr("class").match(/active$/)) {
      $("#tagButton").addClass("active btn-tag");
      $("#geoButton").removeClass("active btn-geo");
      $("#geoButton").addClass("btn-default btn-geo-hover");
      $("#map-canvas").css("display", "none");
      $("#formGeo").css("display", "none");
      $("#formTag").removeAttr("style");
      $("#popularTag").removeAttr("style");
      $("#buttonMore").removeAttr("style");
      $("#status").text("Search by tag");
      $(".block_second").css("border-color", "#FFA500");
      $(".popularLocTitle").css("display", "none");
      displayPopularTag();
    }
  } else {
    if ($("#geoButton").attr("class").match(/active$/)) {
      initialUpdate();
    }
  }
  $("#geoButton").unbind("click").click(function() {
    if (!$(this).attr("class").match(/active$/)) {
      $(this).addClass("active btn-geo");
      $("#geoButton").removeClass("btn-default");
      $("#tagButton").removeClass("active btn-tag");
      $("#tagButton").addClass("btn-default btn-tag-hover");
      $("#map-canvas").css("display", "");
      $("#formTag").css("display", "none");
      $("#formGeo").removeAttr("style");
      $("#popularTag").css("display", "none");
      $("#popularLoc").removeAttr("style");
      $(".popularLocTitle").removeAttr("style");
      $("#tagButton").removeClass("active btn-primary");
      $("#buttonMore").css("display", "none");
      $("#status").text("Search by location");
      return $(".block_second").css("border-color", "#FF6347");
    }
  });
  return $("#tagButton").unbind("click").click(function() {
    if (!$(this).attr("class").match(/active$/)) {
      $(this).addClass("active btn-tag");
      $("#geoButton").removeClass("active btn-geo");
      $("#geoButton").addClass("btn-default btn-geo-hover");
      $("#map-canvas").css("display", "none");
      $("#formGeo").css("display", "none");
      $("#formTag").removeAttr("style");
      $("#popularLoc").css("display", "none");
      $("#popularTag").removeAttr("style");
      $("#status").text("Search by tag");
      $("#buttonMore").removeAttr("style");
      $(".block_second").css("border-color", "#FFA500");
      $(".popularLocTitle").css("display", "none");
      return displayPopularTag();
    }
  });
});

$(document).ready(function() {
  $("#searchButtonGeo").unbind("click").click(function() {
    $(this).button("loading");
    return updateByAddr($("#searchTextGeo").val());
  });
  $("#searchButtonTag").unbind("click").click(function() {
    $(this).button("loading");
    updatePhotosByTag($("#searchTextTag").val());
    return $("#status").text("Searching by tag: \"" + $("#searchTextTag").val() + "\"");
  });
  $("#searchTextGeo").bind("keypress", function(e) {
    var code;
    code = e.keyCode || e.which;
    if (code === 13) {
      $("#searchButtonGeo").button("loading");
      updateByAddr($("#searchTextGeo").val());
      e.preventDefault();
      return false;
    }
  });
  return $("#searchTextTag").bind("keypress", function(e) {
    var code;
    code = e.keyCode || e.which;
    if (code === 13) {
      $("#searchButtonTag").button("loading");
      updatePhotosByTag($("#searchTextTag").val());
      $("#status").text("Searching by tag: \"" + $("#searchTextTag").val() + "\"");
      e.preventDefault();
      return false;
    }
  });
});

$(document).ready(function() {
  return $("#notauth").unbind("click").click(function() {
    $.removeCookie("insta_token");
    return location.reload();
  });
});
