// Generated by CoffeeScript 1.7.1
var addrToUrl, tagToUrl;

addrToUrl = function(address) {
  var addressFormatted;
  addressFormatted = address.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-$/, "");
  return window.location.href = window.location.href.replace(/#.*/g, "") + "#addr-" + addressFormatted;
};

tagToUrl = function(tag) {
  window.location.href = window.location.href.replace(/#.*/g, "") + "#tag-" + tag;
  return window.location.href = window.location.href.replace(/#.*/g, "") + "#tag-" + tag;
};
